### ISSUE TITLE
how to compile

### ISSUE THREAD

**Issue by mmb4** [tosate/csv-to-homebridge-knx#1]
Hi,

Is this project in a working state? If so, is it possible to give instructions on how to compile (on MacOs).
Looks interesting!

**Comment by tosate** [comment]
Hi @mmb4 I am using the project myself. I suggest to use the eclipse IDE. Checkout the code, import it as a maven project. The eclipse IDE will than take care about downloading the dependent libraries.
Provide a CSV file as an input. The path can be configured in the application.properties file.
Invoke the App.java class and you will end up with knx_config.json file.
This file is used by the homebridge-knx plugin
